export const neighbourhoods = [
    { "id": 1, "name": "West Humber-Clairville (1)" },
    { "id": 2, "name": "Mount Olive-Silverstone-Jamestown (2)" },
    { "id": 3, "name": "Thistletown-Beaumond Heights (3)" },
    { "id": 4, "name": "Rexdale-Kipling (4)" },
    { "id": 5, "name": "Elms-Old Rexdale (5)" },
    { "id": 6, "name": "Kingsview Village-The Westway (6)" },
    { "id": 7, "name": "Willowridge-Martingrove-Richview (7)" },
    { "id": 8, "name": "Humber Heights-Westmount (8)" },
    { "id": 9, "name": "Edenbridge-Humber Valley (9)" },
    { "id": 10, "name": "Princess-Rosethorn (10)" },
    { "id": 11, "name": "Eringate-Centennial-West Deane (11)" },
    { "id": 12, "name": "Markland Wood (12)" },
    { "id": 13, "name": "Etobicoke West Mall (13)" },
    { "id": 15, "name": "Kingsway South (15)" },
    { "id": 16, "name": "Stonegate-Queensway (16)" },
    { "id": 18, "name": "New Toronto (18)" },
    { "id": 19, "name": "Long Branch (19)" },
    { "id": 20, "name": "Alderwood (20)" },
    { "id": 21, "name": "Humber Summit (21)" },
    { "id": 22, "name": "Humbermede (22)" },
    { "id": 23, "name": "Pelmo Park-Humberlea (23)" },
    { "id": 24, "name": "Black Creek (24)" },
    { "id": 25, "name": "Glenfield-Jane Heights (25)" },
    { "id": 27, "name": "York University Heights (27)" },
    { "id": 28, "name": "Rustic (28)" },
    { "id": 29, "name": "Maple Leaf (29)" },
    { "id": 30, "name": "Brookhaven-Amesbury (30)" },
    { "id": 31, "name": "Yorkdale-Glen Park (31)" },
    { "id": 32, "name": "Englemount-Lawrence (32)" },
    { "id": 33, "name": "Clanton Park (33)" },
    { "id": 34, "name": "Bathurst Manor (34)" },
    { "id": 35, "name": "Westminster-Branson (35)" },
    { "id": 36, "name": "Newtonbrook West (36)" },
    { "id": 37, "name": "Willowdale West (37)" },
    { "id": 38, "name": "Lansing-Westgate (38)" },
    { "id": 39, "name": "Bedford Park-Nortown (39)" },
    { "id": 40, "name": "St.Andrew-Windfields (40)" },
    { "id": 41, "name": "Bridle Path-Sunnybrook-York Mills (41)" },
    { "id": 42, "name": "Banbury-Don Mills (42)" },
    { "id": 43, "name": "Victoria Village (43)" },
    { "id": 44, "name": "Flemingdon Park (44)" },
    { "id": 46, "name": "Pleasant View (46)" },
    { "id": 47, "name": "Don Valley Village (47)" },
    { "id": 48, "name": "Hillcrest Village (48)" },
    { "id": 49, "name": "Bayview Woods-Steeles (49)" },
    { "id": 50, "name": "Newtonbrook East (50)" },
    { "id": 52, "name": "Bayview Village (52)" },
    { "id": 53, "name": "Henry Farm (53)" },
    { "id": 54, "name": "O`Connor Parkview (54)" },
    { "id": 55, "name": "Thorncliffe Park (55)" },
    { "id": 56, "name": "Leaside-Bennington (56)" },
    { "id": 57, "name": "Broadview North (57)" },
    { "id": 58, "name": "Old East York (58)" },
    { "id": 59, "name": "Danforth-East York (59)" },
    { "id": 60, "name": "Woodbine-Lumsden (60)" },
    { "id": 61, "name": "Taylor Massey (61)" },
    { "id": 62, "name": "East End Danforth (62)" },
    { "id": 63, "name": "The Beaches (63)" },
    { "id": 64, "name": "Woodbine Corridor (64)" },
    { "id": 65, "name": "Greenwood-Coxwell (65)" },
    { "id": 66, "name": "Danforth (66)" },
    { "id": 67, "name": "Playter Estates-Danforth (67)" },
    { "id": 68, "name": "North Riverdale (68)" },
    { "id": 69, "name": "Blake-Jones (69)" },
    { "id": 70, "name": "South Riverdale (70)" },
    { "id": 71, "name": "Cabbagetown-South St. James Town (71)" },
    { "id": 72, "name": "Regent Park (72)" },
    { "id": 73, "name": "Moss Park (73)" },
    { "id": 74, "name": "North St. James Town (74)" },
    { "id": 78, "name": "Kensington-Chinatown (78)" },
    { "id": 79, "name": "University (79)" },
    { "id": 80, "name": "Palmerston-Little Italy (80)" },
    { "id": 81, "name": "Trinity-Bellwoods (81)" },
    { "id": 83, "name": "Dufferin Grove (83)" },
    { "id": 84, "name": "Little Portugal (84)" },
    { "id": 85, "name": "South Parkdale (85)" },
    { "id": 86, "name": "Roncesvalles (86)" },
    { "id": 87, "name": "High Park-Swansea (87)" },
    { "id": 88, "name": "High Park North (88)" },
    { "id": 89, "name": "Runnymede-Bloor West Village (89)" },
    { "id": 90, "name": "Junction Area (90)" },
    { "id": 91, "name": "Weston-Pelham Park (91)" },
    { "id": 92, "name": "Corso Italia-Davenport (92)" },
    { "id": 94, "name": "Wychwood (94)" },
    { "id": 95, "name": "Annex (95)" },
    { "id": 96, "name": "Casa Loma (96)" },
    { "id": 97, "name": "Yonge-St. Clair (97)" },
    { "id": 98, "name": "Rosedale-Moore Park (98)" },
    { "id": 99, "name": "Mount Pleasant East (99)" },
    { "id": 100, "name": "Yonge-Eglinton (100)" },
    { "id": 101, "name": "Forest Hill South (101)" },
    { "id": 102, "name": "Forest Hill North (102)" },
    { "id": 103, "name": "Lawrence Park South (103)" },
    { "id": 105, "name": "Lawrence Park North (105)" },
    { "id": 106, "name": "Humewood-Cedarvale (106)" },
    { "id": 107, "name": "Oakwood Village (107)" },
    { "id": 108, "name": "Briar Hill-Belgravia (108)" },
    { "id": 109, "name": "Caledonia-Fairbank (109)" },
    { "id": 110, "name": "Keelesdale-Eglinton West (110)" },
    { "id": 111, "name": "Rockcliffe-Smythe (111)" },
    { "id": 112, "name": "Beechborough-Greenbrook (112)" },
    { "id": 113, "name": "Weston (113)" },
    { "id": 114, "name": "Lambton Baby Point (114)" },
    { "id": 115, "name": "Mount Dennis (115)" },
    { "id": 116, "name": "Steeles (116)" },
    { "id": 118, "name": "Tam O’Shanter-Sullivan (118)" },
    { "id": 119, "name": "Wexford/Maryvale (119)" },
    { "id": 120, "name": "Clairlea-Birchmount (120)" },
    { "id": 121, "name": "Oakridge (121)" },
    { "id": 122, "name": "Birchcliffe-Cliffside (122)" },
    { "id": 123, "name": "Cliffcrest (123)" },
    { "id": 124, "name": "Kennedy Park (124)" },
    { "id": 125, "name": "Ionview (125)" },
    { "id": 126, "name": "Dorset Park (126)" },
    { "id": 128, "name": "Agincourt South-Malvern West (128)" },
    { "id": 129, "name": "Agincourt North (129)" },
    { "id": 130, "name": "Milliken (130)" },
    { "id": 133, "name": "Centennial Scarborough (133)" },
    { "id": 134, "name": "Highland Creek (134)" },
    { "id": 135, "name": "Morningside (135)" },
    { "id": 136, "name": "West Hill (136)" },
    { "id": 138, "name": "Eglinton East (138)" },
    { "id": 139, "name": "Scarborough Village (139)" },
    { "id": 140, "name": "Guildwood (140)" },
    { "id": 141, "name": "Golfdale-Cedarbrae-Woburn (141)" },
    { "id": 142, "name": "Woburn North (142)" },
    { "id": 143, "name": "West Rouge (143)" },
    { "id": 144, "name": "Morningside Heights (144)" },
    { "id": 145, "name": "Malvern West (145)" },
    { "id": 146, "name": "Malvern East (146)" },
    { "id": 147, "name": "L’Amoreaux West (147)" },
    { "id": 148, "name": "East L’Amoreaux (148)" },
    { "id": 149, "name": "Parkwoods-O’Connor Hills (149)" },
    { "id": 150, "name": "Fenside-Parkwoods (150)" },
    { "id": 151, "name": "Yonge-Doris (151)" },
    { "id": 152, "name": "East Willowdale (152)" },
    { "id": 153, "name": "Avondale (153)" },
    { "id": 154, "name": "Oakdale-Beverley Heights (154)" },
    { "id": 155, "name": "Downsview (155)" },
    { "id": 156, "name": "Bendale-Glen Andrew (156)" },
    { "id": 157, "name": "Bendale South (157)" },
    { "id": 158, "name": "Islington (158)" },
    { "id": 159, "name": "Etobicoke City Centre (159)" },
    { "id": 160, "name": "Mimico-Queensway (160)" },
    { "id": 161, "name": "Humber Bay Shores (161)" },
    { "id": 162, "name": "West Queen West (162)" },
    { "id": 163, "name": "Fort York-Liberty Village (163)" },
    { "id": 164, "name": "Wellington Place (164)" },
    { "id": 165, "name": "Harbourfront-CityPlace (165)" },
    { "id": 166, "name": "St Lawrence-East Bayfront-The Islands (166)" },
    { "id": 167, "name": "Church-Wellesley (167)" },
    { "id": 168, "name": "Downtown Yonge East (168)" },
    { "id": 169, "name": "Bay-Cloverhill (169)" },
    { "id": 170, "name": "Yonge-Bay Corridor (170)" },
    { "id": 171, "name": "Junction-Wallace Emerson (171)" },
    { "id": 172, "name": "Dovercourt Village (172)" },
    { "id": 173, "name": "North Toronto (173)" },
    { "id": 174, "name": "South Eglinton-Davisville (174)" }
  ]
  

// Helper function to get neighbourhood by ID
export const getNeighbourhoodById = (id) => {
  return neighbourhoods.find(nbhd => nbhd.id === parseInt(id))
}

// Helper function to get neighbourhood by name
export const getNeighbourhoodByName = (name) => {
  return neighbourhoods.find(nbhd => nbhd.name.toLowerCase() === name.toLowerCase())
}

// Helper function to search neighbourhoods
export const searchNeighbourhoods = (searchTerm) => {
  return neighbourhoods.filter(nbhd => 
    nbhd.name.toLowerCase().includes(searchTerm.toLowerCase())
  )
} 